### ISSUE TITLE
xlsxr failed to read a xlsx file

### ISSUE THREAD

**Issue by chfw** [pyexcel/pyexcel-xlsxr#1]
https://github.com/pyexcel/pyexcel/issues/152

**Comment by chfw** [comment]
@kvoutyras , if it is OK, could you drop your file here please?

**Comment by kvoutyras** [comment]
I used the following code to read this file: 

import pyexcel_xlsx as px

filename='test_data.xlsx'
d = px.get_data(filename)

Please find the sheet below. Let me know asap when some solution is available :)
[test_data.xlsx](https://github.com/pyexcel/pyexcel-xlsxr/files/2322894/test_data.xlsx)

**Comment by chfw** [comment]
please try pyexcel-xlsxr==0.5.1

for your information: both pyexcel-xlsx and pyexcel-xls is able to read this artefact without problems.

**Comment by chfw** [comment]
please use pyexcel-xlsxr==0.5.2. Previous verison is broken on python 3.x.
