### ISSUE TITLE
Cannot read Excel sheet at work

### ISSUE THREAD

**Issue by ArneBachmannDLR** [pyexcel/pyexcel-xlsxr#5]
I had to insert the following statement at the beginning of `service.py/detect_float|int_value` to avoid a recurring `AttributeError: 'NoneType' object has no attribute 'startswith'`:

```Python3
if not cell_text: return None
```

**Comment by chfw** [comment]
please try if it fixes your issue:

`$ pip install https://github.com/pyexcel/pyexcel-xlsxr/archive/master.zip`

**Comment by ArneBachmannDLR** [comment]
Yes, works now!

**Comment by chfw** [comment]
Thanks. v0.5.3 has been released, containing the fix here.
